version: "3.4"

services:
  cookbook-db-redis:
    image: mmercan/cookbook-db-redis:${TAGVersion}-prod-linux
    build:
      context: ./
      dockerfile: Dockerfile
    # volumes:
    #   - C:\repos\sentinel\Sentinel.Web\Sentinel.Db.Redis:/data
    # command: redis-server --requirepass yourpassword
    # command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
