apiVersion: v1
kind: ConfigMap
metadata:
    name: "{{ include "CookBook.Redis.fullname" . }}-config"
    labels:
        {{- include "CookBook.Redis.labels" . | nindent 4 }}
data:
    redis-config: "databases 8\nmaxclients 2000\nrequirepass \"{{.Values.password}}\"\n\n"
    requirepass: {{.Values.password}}
    servicename: {{ include "CookBook.Redis.fullname" . }}
 {{- if .Values.configmap -}}
{{- range $key, $value := .Values.configmap }}
    {{ $key }}: {{ default "" $value | b64enc | quote }}
{{- end -}}
{{- end }}


