version: "3.4"

services:
  cookbook-admin-ui:
    image: cookbook-admin-ui:${TAGVersion}-dev-linux
    build:
      target: develop
      context: .
      dockerfile: CookBook.Admin.UI/Dockerfile
    volumes:
      - .\CookBook.Admin.UI:/var/www/html
    entrypoint: ng serve --host 0.0.0.0 --poll 1 --disable-host-check
    #entrypoint: npm run startdocker
    ports:
      - "4200:4200"

  cookbook-recipe-ui:
    image: cookbook-recipe-ui:${TAGVersion}-dev-linux
    build:
      target: develop
      context: .
      dockerfile: CookBook.Recipe.UI/Dockerfile
    volumes:
      - .\CookBook.Recipe.UI:/var/www/html
    entrypoint: ng serve --host 0.0.0.0 --poll 1 --disable-host-check
    #entrypoint: npm run startdocker
    ports:
      - "4201:4200"

  cookbook-comms-api:
    image: cookbook-comms-api:${TAGVersion}-dev-linux
    build:
      target: develop
      context: .
      dockerfile: CookBook.Comms.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - .:/src
    entrypoint: dotnet watch run --verbose --no-launch-profile --configuration Debug
    ports:
      - "5005:80"
      - "5006:81"

  cookbook-recipe-api:
    image: cookbook-recipe-api:${TAGVersion}-dev-linux
    build:
      target: develop
      context: .
      dockerfile: CookBook.Recipe.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - .:/src
    entrypoint: dotnet watch run --verbose --no-launch-profile --configuration Debug
    ports:
      - "5007:80"

  cookbook-comms-handler:
    image: cookbook-comms-handler:${TAGVersion}-dev-linux
    build:
      target: develop
      context: .
      dockerfile: CookBook.Comms.Handler/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - .:/src
    entrypoint: dotnet watch run --verbose --no-launch-profile --configuration Debug

  cookbook-recipe-handler:
    image: cookbook-recipe-handler:${TAGVersion}-dev-linux
    build:
      target: develop
      context: .
      dockerfile: CookBook.Recipe.Handler/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - .:/src
    entrypoint: dotnet watch run --verbose --no-launch-profile --configuration Debug

  cookbook-db-mongodb:
    image: cookbook-db-mongodb:${TAGVersion}-dev-linux
    build:
      context: ./CookBook.MongoDB
      dockerfile: Dockerfile
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=cookbook
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hbMnztmZ4w9JJTGZ
      - MONGODB_DATABASE=cookbook
    # volumes:
    #   - ./data:/data/db
    #   # - cookbookmongodata:/data/db
    ports:
      - 27017:27017

  cookbook-redis:
    image: cookbook-redis:${TAGVersion}-dev-linux
    build:
      context: ./CookBook.Redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"

  cookbook-rabbitmq:
    image: cookbook-rabbitmq:${TAGVersion}-dev-linux
    build:
      context: ./CookBook.RabbitMQ
      dockerfile: Dockerfile
    labels:
      NAME: "rabbitmq1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    #   RABBITMQ_DEFAULT_USER: "rabbitmq"
    #   RABBITMQ_DEFAULT_PASS: "rabbitmq"
    #   RABBITMQ_DEFAULT_VHOST: "/"
    # volumes:
    # - ./config/:/etc/rabbitmq/
    # - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
    # - "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
    ports:
      - "15672:15672"
      - "5672:5672"
