version: "3.4"

services:
  cookbook-api-healthcheck:
    image: mmercan/cookbook-api-healthcheck:${TAGVersion}-prod-linux
    build:
      target: final
      context: ../
      dockerfile: CookBook.HealthCheck.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
