apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: comms-api-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    # - port:
    #     number: 80
    #     name: http
    #     protocol: HTTP
    - port:
        number: 81
        name: grpc
        protocol: GRPC
      hosts:
        - "comms.cookbook.mercan.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cookbook-api-vs
spec:
  hosts:
    - "comms.cookbook.mercan.io"
  gateways:
    - comms-api-gateway
  http:
    - match:
        - uri:
            prefix: /
        - uri:
            exact: /index.html
        - uri:
            prefix: /static
        - uri:
            prefix: /api/v1/products
      route:
        - destination:
            host: {{ include "comms-api.fullname" . }}
            port:
              number: 81