apiVersion: v1
kind: ConfigMap
metadata:
    name: "{{ include "CookBook.RabbitMQ.fullname" . }}-config"
    labels:
    {{- include "CookBook.RabbitMQ.labels" . | nindent 6 }}
data:
 requirepass: {{.Values.password}}
 servicename: {{ include "CookBook.RabbitMQ.fullname" . }}
 {{- if .Values.configmap -}}
{{- range $key, $value := .Values.configmap }}
 {{ $key }}: {{ default "" $value | b64enc | quote }}
{{- end -}}
{{- end }}


