apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "CookBook.RabbitMQ.fullname" . }}-secret"
  labels:
    {{- include "CookBook.RabbitMQ.labels" . | nindent 4 }}
  annotations:
    {{- include "CookBook.RabbitMQ.annotations" . | nindent 4 }}
type: "Opaque"
data:
 {{- if .Values.secrets -}}
{{- range $key, $value := .Values.secrets }}
 {{ $key }}: {{ default "" $value | b64enc | quote }}
{{- end -}}
{{- end }}