apiVersion: v1
kind: Service
metadata:
  name: {{ include "CookBook.RabbitMQ.fullname" . }}-http
  labels:                    
    {{- include "CookBook.RabbitMQ.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - name: http               
    port: 80               
    targetPort: 15672
    protocol: TCP            
  selector:
    {{- include "CookBook.RabbitMQ.selectorLabels" . | nindent 4 }}

