apiVersion: v1
kind: Service
metadata:
  name: {{ include "CookBook.RabbitMQ.fullname" . }}-tcp
  labels:                    
    {{- include "CookBook.RabbitMQ.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:        
  - name: transport          
    port: 5672               
    targetPort: 5672
    protocol: TCP
  selector:
    {{- include "CookBook.RabbitMQ.selectorLabels" . | nindent 4 }}

