version: "3.4"

services:
  sentinel-db-mongodb:
    image: mmercan/cookbook-db-mongodb:${TAGVersion}-prod-linux
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=cookbook
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hbMnztmZ4w9JJTGZ
      - MONGODB_DATABASE=cookbook
    ports:
      - 27017:27017
