{{- if .Values.configmap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "CookBook.Admin.UI.fullname" . }}-config"
data:
 {{- if .Values.configmap -}}
{{- range $key, $value := .Values.configmap }}
 {{ $key }}: {{ default "" $value  | quote }}
{{- end -}}
{{- end }}

{{- end }}

