{{- $name := include "CookBook.Admin.UI.fullname" . -}}
{{- $cfgname := printf "%s-%s" $name "config" -}}
{{- $secretname := printf "%s-%s" $name "secret" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "CookBook.Admin.UI.fullname" . }}
  labels:
    {{- include "CookBook.Admin.UI.labels" . | nindent 4 }}
  annotations:
    {{- include "CookBook.Admin.UI.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "CookBook.Admin.UI.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "CookBook.Admin.UI.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "CookBook.Admin.UI.annotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "CookBook.Admin.UI.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.configmap .Values.secrets }}
          envFrom:
          {{- end }}
          {{- if .Values.configmap }}
            - configMapRef:
                name: {{ $cfgname }}
          {{- end }}
          {{- if .Values.secrets }}   
            - secretRef:
                name: {{ $secretname }}
           {{- end }}
          env:
            - name: buildnumber
              value: {{ .Values.buildnumber | quote }}
            - name: branch
              value: {{  .Values.branch | quote }}
          {{- if (.Values.env) and  (.Values.env.values) -}}
          {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end -}}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
