apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cookbook-api-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "api.cookbook.mercan.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cookbook-api-vs
spec:
  hosts:
    - "api.cookbook.mercan.io"
  gateways:
    - cookbook-api-gateway
  http:
    - match:
        - uri:
            prefix: /
        - uri:
            exact: /index.html
        - uri:
            exact: /logout
        - uri:
            prefix: /static
        - uri:
            prefix: /api/v1/products
      route:
        - destination:
            host: {{ include "cookbook-api.fullname" . }}
            port:
              number: {{ .Values.service.port }}