{{- if .Values.istio.enabled -}}
{{- $host := printf "%s.%s.%s" .Chart.Name .Values.environment .Values.hostdomain -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name:  {{ include "CookBook.MongoDB.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 27017
        name: MONGO-27017
        protocol: MONGO
      hosts:
        - {{ $host }}
{{- end }}