# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - "*"
    exclude:
      - features/experimental/*
  paths:
    include:
      - Comms.Api/*
      - Comms.Api.Tests/*
      - Helm/cookbook/charts/comms-api/*

stages:
  - stage: build
    jobs:
      - job: build_comms_api
        displayName: Build Comms Api
        pool:
          name: Hosted Ubuntu 1604
        steps:
          - task: DockerCompose@0
            displayName: "Build Test Image"
            inputs:
              containerregistrytype: "Container Registry"
              dockerRegistryEndpoint: DockerHub
              dockerComposeFile: "Comms.Api/docker-compose-test.yml"
              dockerComposeFileArgs: "TAGVersion=01"
              action: "Build services"
              additionalImageTags: "$(Build.BuildNumber)"
              includeLatestTag: true
              arguments: "--build-arg buildtime_APPID=$(buildtime_APPID)  --build-arg buildtime_APPSECRET=$(buildtime_APPSECRET) --build-arg buildtime_ADID=$(buildtime_ADID) --build-arg buildtime_SONARKEY=$(buildtime_SONARKEY)"
# pool:
#   vmImage: "ubuntu-latest"

# steps:
#   - script: echo Hello, world!
#     displayName: "Run a one-line script"

#   - script: |
#       echo Add other tasks to build, test, and deploy your project.
#       echo See https://aka.ms/yaml
#     displayName: "Run a multi-line script"
