api-comms-test:
  image: api-comms-test
  build:
    target: test
    context: ../
    dockerfile: Comms.Api/Dockerfile-test
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - DOTNET_USE_POLLING_FILE_WATCHER=1
