version: "3.4"

services:
  comms-api:
    image: matttestacr01.azurecr.io/api-comms:${TAGVersion}-prod-linux
    build:
      target: final
      context: ../
      dockerfile: Comms.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
  api-comms-test:
    image: sentinel-api-comms-test
    build:
      target: test
      context: ../
      dockerfile: Comms.Api/Dockerfile-test
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
