version: "3.4"

services:
  sentinel-api-comms-test:
    image: sentinel-api-comms-test
    build:
      target: test
      context: ../
      dockerfile: Comms.Api/Dockerfile-linux-test
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
