version: "3.4"

services:
  cookbook-api:
    image: matttestacr01.azurecr.io/api-cookbook:${TAGVersion}-prod-linux
    build:
      target: final
      context: ../
      dockerfile: CookBook.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
